version: '3.8'
services:
  app:
    container_name: api
    build:
      context: .
    network_mode: "host"
    volumes:
      - /mnt/d/CuaimaTeam/videos:/app/videos
      - /mnt/d/CuaimaTeam/hls:/app/hls_output
      - /etc/letsencrypt:/etc/letsencrypt

  nginx:
    container_name: server
    image: nginx:alpine
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /mnt/d/CuaimaTeam/hls:/app/hls_output
      - /etc/letsencrypt:/etc/letsencrypt

    # entrypoint: ["sh", "-c", "lsof -t -i:2001 | xargs -r kill -9 && nginx -g 'daemon off;'"]

x-scripts:
  pre-up:
    command: ./free_port.sh
