version: '3.8'

services:
  app:
    container_name: api
    build:
      context: .
    network_mode: "host"
    user: "root"
    volumes:
      - ./app/videos:/app/videos:rw 
      - ./app/hls:/app/hls_output  # Carpeta de salida HLS
      - ./app/public:/app/public  # Carpeta de salida HLS
    deploy:
      resources:
        limits:
          memory: "5GB"  # Limita a 5GB de RAM
          cpus: "0.90"    # Limita al 90% de la CPU