version: '3.8'

services:
  app:
    container_name: api
    build:
      context: .
    network_mode: "host"
    volumes:
      - ./videos:/app/videos:ro  # Solo lectura
      - ./app/hls:/app/hls_output:rw  # Carpeta de salida HLS
      - ./app/public:/app/public  # Carpeta de salida HLS
