version: '3.8'

services:
  app:
    container_name: api
    build:
      context: .
    network_mode: "host"
    volumes:
      - ./app/videos:/app/videos:ro  # Solo lectura
      - ./app/hls:/app/hls_output  # Carpeta de salida HLS
