version: '3.8'
services:
  app:
    container_name: api
    build:
      context: .
    network_mode: "host"  # Usar la red del host para menor latencia
    volumes:
      - /mnt/d/CuaimaTeam/videos:/app/videos
      - /mnt/d/CuaimaTeam/hls:/app/hls_output

  nginx:
    container_name: server
    image: nginx:alpine
    network_mode: "host"  # NGINX también usa la red del host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /mnt/d/CuaimaTeam/hls:/app/hls_output
