version: '3.8'
services:
  app:
    build:
      context: .
    network_mode: "host"  # Usar la red del host para menor latencia
    volumes:
      - ./app/videos:/app/videos
      - ./app/hls_output:/app/hls_output

  nginx:
    image: nginx:alpine
    network_mode: "host"  # NGINX también usa la red del host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app/hls_output:/app/hls_output
